### PR TITLE
📁 Added a world.zip file to allow better compatibilty with automated systems.

### PR DESCRIPTION
**Pull request by Kalitsune**
RAR is not a very open format and as such is not very well supported, especially on automated systems like itzg/docker-minecraft-server or linux in general. I did not remove the .rar file for compatibility reasons but instead proposed an alternative archive format.

### CODE REVIEW

**Comment by Linj1k** [comment]
Thanks to you, I hardly ever use dockers etc.., I hadn't thought of that. have Good day 🙂

**Comment by Kalitsune** [comment]
Thank you for being so reactive! I'm glad to see that this piece of the Minecraft history has been updated!

**Comment by Linj1k** [comment]
No worries, thanks to you above all

**Comment by Linj1k** [comment]
I took care of putting it on the spigot page

**Pull request merged**
